### ISSUE TITLE
Game Style enhancements with Cascading Style Sheets

### ISSUE THREAD

**Issue by naomidonato** [rbaker26/TicTacToe#26]

**Comment by naomidonato** [comment]
Includes UI enhancements of GUI designs and elements.

**Comment by Autofire** [comment]
Hate to nitpick, but... if I'm an end user, I might say this:

"What's a CSS? Is it... tasty?"

Our descriptions can be as technical as we need them to be, but the titles should be understandable by the layman.

**Comment by naomidonato** [comment]
Cascading Style Sheets

**Comment by Autofire** [comment]
"What's a Cascading Style Sheet? Is it pretty?"
